apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-schema
spec:
  template:
    spec:
      containers:
      - name: psql-client
        image: postgres:15-alpine
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        command: 
          - /bin/sh
          - -c
          - |
            # 2. Added a wait-loop to ensure Postgres is actually up
            echo "Waiting for postgres-service..."
            until pg_isready -h postgres-service -U admin_user; do
              sleep 2
            done

            echo "Applying schema..."
            psql -h postgres-service -U admin_user -d sales_db -f /scripts/schema.sql
        volumeMounts:
        - name: schema-vol
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: schema-vol
        configMap:
          name: db-schema-config
  backoffLimit: 4